// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using MyModels;
using SkyModel;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(SkyDbContext), typeof(SkyDbContextModel))]
