// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyModels
{
    public partial class SkyDbContextModel
    {
        private SkyDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b5262653-3228-407e-a855-ea4127138cda"), entityTypeCount: 6)
        {
        }

        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var minIO = MinIOEntityType.Create(this);
            var newsArticle = NewsArticleEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var productDetail = ProductDetailEntityType.Create(this);
            var user = UserEntityType.Create(this);

            MinIOEntityType.CreateForeignKey1(minIO, newsArticle);
            MinIOEntityType.CreateForeignKey2(minIO, productDetail);
            ProductEntityType.CreateForeignKey1(product, category);
            ProductEntityType.CreateForeignKey2(product, productDetail);
            ProductEntityType.CreateForeignKey3(product, user);

            CategoryEntityType.CreateAnnotations(category);
            MinIOEntityType.CreateAnnotations(minIO);
            NewsArticleEntityType.CreateAnnotations(newsArticle);
            ProductEntityType.CreateAnnotations(product);
            ProductDetailEntityType.CreateAnnotations(productDetail);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "9.0.0");
            AddAnnotation("Proxies:ChangeTracking", false);
            AddAnnotation("Proxies:CheckEquality", false);
            AddAnnotation("Proxies:LazyLoading", true);
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
